sample = {
    "gemini-1": {
        "content": {
            "Image": "0001_C0268508F_p.jpg",
            "verbatimCollectors": "leg. M. Fleischer nr. B 2692",
            "collectedBy": "M. Fleischer",
            "secondaryCollectors": "N/A",
            "recordNumber": "B 2692",
            "verbatimEventDate": "25.3.1903",
            "minimumEventDate": "1903-03-25",
            "maximumEventDate": "N/A",
            "verbatimIdentification": "Macromitrium",
            "latestScientificName": "Macromitrium",
            "identifiedBy": "N/A",
            "verbatimDateIdentified": "N/A",
            "associatedTaxa": "N/A",
            "country": "Australia",
            "firstPoliticalUnit": "Queensland",
            "secondPoliticalUnit": "N/A",
            "municipality": "Eumundi",
            "verbatimLocality": "Australien: Queensland, Eumundi (ca. 100 km nördlich Brisbane), Urwald.",
            "locality": "Eumundi (ca. 100 km nördlich Brisbane), Urwald (forest)",
            "habitat": "Urwald (forest)",
            "verbatimElevation": "N/A",
            "verbatimCoordinates": "N/A",
            "otherCatalogNumbers": "1076699 | 1044122",
            "originalMethod": "Typed",
            "typeStatus": ""
        },
        "data": {
            "old version": "base",
            "created by": "DanS",
            "input tokens": 1773,
            "output tokens": 251,
            "input cost $": 1.0,
            "output cost $": 2.0,
            "time to create/edit": 0.8771886825561523
        }
    },
    "gemini-2": {
        "content": {
            "Image": "0001_C0268508F_p.jpg",
            "verbatimCollectors": "leg. M. Fleischer nr. B 2692",
            "collectedBy": "M. Fleischer",
            "secondaryCollectors": "N/A",
            "recordNumber": "B 2692",
            "verbatimEventDate": "25.3.1903",
            "minimumEventDate": "1903-03-25",
            "maximumEventDate": "N/A",
            "verbatimIdentification": "Macromitrium",
            "latestScientificName": "Macromitrium",
            "identifiedBy": "N/A",
            "verbatimDateIdentified": "N/A",
            "associatedTaxa": "N/A",
            "country": "Australia",
            "firstPoliticalUnit": "Queensland",
            "secondPoliticalUnit": "N/A",
            "municipality": "Eumundi",
            "verbatimLocality": "Australien: Queensland, Eumundi (ca. 100 km nördlich Brisbane), Urwald.",
            "locality": "Eumundi (ca. 100 km nördlich Brisbane), Urwald",
            "habitat": "Urwald",
            "verbatimElevation": "N/A",
            "verbatimCoordinates": "N/A",
            "otherCatalogNumbers": "1076699 | 1044122",
            "originalMethod": "Mix of Handwritten and Typed",
            "typeStatus": ""
        },
        "data": {
            "old version": "gemini-1",
            "created by": "DanS",
            "input tokens": 1773,
            "output tokens": 250,
            "input cost $": 3.0,
            "output cost $": 4.0,
            "overall old version": "base",
            "overall created by": "DanS",
            "overall input tokens": 1773,
            "overall output tokens": 250,
            "overall input cost $": 0.0,
            "overall output cost $": 0.0
        }
    },

    "gemini-3": {
        "content": {
            "Image": "0001_C0268508F_p.jpg",
            "verbatimCollectors": "leg. M. Fleischer nr. B 2692",
            "collectedBy": "M. Fleischer",
            "secondaryCollectors": "N/A",
            "recordNumber": "B 2692",
            "verbatimEventDate": "25.3.1903",
            "minimumEventDate": "1903-03-25",
            "maximumEventDate": "N/A",
            "verbatimIdentification": "Macromitrium",
            "latestScientificName": "Macromitrium",
            "identifiedBy": "N/A",
            "verbatimDateIdentified": "N/A",
            "associatedTaxa": "N/A",
            "country": "Australia",
            "firstPoliticalUnit": "Queensland",
            "secondPoliticalUnit": "N/A",
            "municipality": "Eumundi",
            "verbatimLocality": "Australien: Queensland, Eumundi (ca. 100 km nördlich Brisbane), Urwald.",
            "locality": "Eumundi (ca. 100 km nördlich Brisbane), Urwald",
            "habitat": "Urwald",
            "verbatimElevation": "N/A",
            "verbatimCoordinates": "N/A",
            "otherCatalogNumbers": "1076699 | 1044122",
            "originalMethod": "Mix of Handwritten and Typed",
            "typeStatus": ""
        },
        "data": {
            "old version": "gemini-2",
            "created by": "DanS",
            "input tokens": 1773,
            "output tokens": 250,
            "input cost $": 5.0,
            "output cost $": 6.0,
            "overall old version": "base",
            "overall created by": "DanS",
            "overall input tokens": 1773,
            "overall output tokens": 250,
            "overall input cost $": 0.0,
            "overall output cost $": 0.0
        }
    }
}

